version: "3"

services:
  timeadventure-proxy:
    image: nginx:stable
    ports:
      - "8001:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    networks:
      - internet
      - no-internet
  timeadventure:
    build: ./timeAdventure
    container_name: 'timeAdventure'
    restart: 'unless-stopped'
    volumes: 
      # using :ro to prevent write file
      - ./timeAdventure/src/:/var/www/html/:ro
    networks:
      - no-internet
networks:
  internet: {}
  no-internet:
    internal: true