version: "3"

services:
  timeadventure:
    build: ./timeAdventure
    ports:
      - "3006:80"
    container_name: 'timeAdventure'
    restart: 'unless-stopped'
    volumes: 
      # using :ro to prevent write file
      - ./timeAdventure/src/:/var/www/html/:ro
    networks:
      - internet

networks:
  internet: {}